class CheckingError(Exception):
   pass

class LoginError(Exception):
    pass
